// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/labstack/echo/v4"
	"kite/internal/api/handlers/mock"
	"kite/internal/configs"
	"kite/internal/database"
	"kite/internal/repositories"
	"kite/internal/services"
)

// Injectors from wire.go:

func InitializeApp(cfg *configs.MySQLConfig, echo2 *echo.Echo) (*Server, error) {
	mySQLConnection := database.NewMySQLConnection(cfg)
	apiRepository := repositories.NewApiRepository(mySQLConnection)
	apiService := services.NewApiService(apiRepository)
	apiHandler := mock.NewApiHandler(apiService)
	server := NewServer(echo2, mySQLConnection, apiHandler)
	return server, nil
}

// wire.go:

var RepositorySet = wire.NewSet(repositories.NewApiRepository)

var ServiceSet = wire.NewSet(services.NewApiService)

var HandlerSet = wire.NewSet(mock.NewApiHandler)
