server:
  port: 80
  shutdown_timeout: 10

database:
  driver: postgres
  host: localhost
  port: 5432
  name: ${DB_USER}
  password: ${DB_PASSWORD}
  ssl_mode: disable
  max_idle_conn: 5
  max_open_conn: 100
  max_lifetime: 3600

log:
  level: info
  encoding: json
  dev: true