server:
  port: 80
  shutdown_timeout: 10

database:
  driver: mysql
  host: localhost
  port: 3306
  name: newcounter
  user: root
  password: Xbcd20198$
  ssl_mode: disable
  charset: utf8mb4
  max_idle_conn: 5
  max_open_conn: 100
  max_lifetime: 3600

log:
  level: info
  encoding: json
  dev: true